### ISSUE TITLE
Set Suport Garage

### ISSUE THREAD

**Issue by erokoder** [rsporny/homebridge-gpio-blinds#1]
Hello, 
Could you change code that support garage accessories with same code logic. (up,down,duration for up and down)
I only need another Type accessories in Home App?
Best Regards,
Rade

**Comment by toshibochan** [comment]
You can use https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor

**Comment by rsporny** [comment]
Hi,
Garage door opener should have another logic. Probably you don't need to set target position of garage door, you would rather go with simple open/close plus reading current status.

However, you could use this code as garage door opener as it is. Just be careful when connecting to relay switch - my blinds need 230V, garage door operator probably only 24VDC. Icon of the accessory in Home app will be blinds. Changing only the service (type) to GarageDoorOpener will not work because of different characteristics used.

I'll be implementing garage door opener later this year. It's gonna have the same architecture (rpio lib, no root for gpio) and setup, slightly different logic with use of reed switch. For now, I suggest you to search for existing plugins as @toshibochan mentioned or on https://www.npmjs.com/search?q=homebridge+garage+gpio
